version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: check-changed-paths
          base-revision: master
          mapping: |
            rtl4332mqtt-interlogix-autodiscovery:
              - aarch64
              - amd64
              - armv7
              - i386
            tshark:
              - aarch64
              - amd64
              - armv7
              - i386
            oauth2-proxy:
              - aarch64
              - amd64
              - armv7
              - i386
          config-path: .circleci/continue_config.yml

workflows:
  build-and-publish:
    jobs:
      - build:
          matrix:
            parameters:
              path: ["rtl4332mqtt-interlogix-autodiscovery", "tshark", "oauth2-proxy"]
              target-arch: ["aarch64", "amd64", "armv7", "i386"]
      - publish:
          matrix:
            parameters:
              path: ["rtl4332mqtt-interlogix-autodiscovery", "tshark", "oauth2-proxy"]
              target-arch: ["aarch64", "amd64", "armv7", "i386"]