version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: check-changed-paths
          base-revision: master
          mapping: |
            <<#matrix.path>>
              <<.>>/* build-<<.>>-aarch64-arm-executor true
              <<.>>/* build-<<.>>-amd64-amd-executor true
              <<.>>/* build-<<.>>-armv7-arm-executor true
              <<.>>/* build-<<.>>-i386-arm-executor true
            <</matrix.path>>
            <<#publish.path>>
              <<.>>-aarch64-arm-executor/* publish true
              <<.>>-amd64-amd-executor/* publish true
              <<.>>-armv7-arm-executor/* publish true
              <<.>>-i386-arm-executor/* publish true
            <</publish.path>>
          config-path: .circleci/continue_config.yml
