version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: check-changed-paths
          base-revision: master
          mapping: |
            rtl4332mqtt-interlogix-autodiscovery:
              aarch64:
                arm-executor: "build-rtl4332mqtt-interlogix-autodiscovery-aarch64-arm-executor"
                amd-executor: "build-rtl4332mqtt-interlogix-autodiscovery-aarch64-amd-executor"
              amd64:
                arm-executor: "build-rtl4332mqtt-interlogix-autodiscovery-amd64-arm-executor"
                amd-executor: "build-rtl4332mqtt-interlogix-autodiscovery-amd64-amd-executor"
              armv7:
                arm-executor: "build-rtl4332mqtt-interlogix-autodiscovery-armv7-arm-executor"
                amd-executor: "build-rtl4332mqtt-interlogix-autodiscovery-armv7-amd-executor"
              i386:
                arm-executor: "build-rtl4332mqtt-interlogix-autodiscovery-i386-arm-executor"
                amd-executor: "build-rtl4332mqtt-interlogix-autodiscovery-i386-amd-executor"
            publish:
              rtl4332mqtt-interlogix-autodiscovery:
                aarch64:
                  arm-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-aarch64-arm-executor"
                  amd-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-aarch64-amd-executor"
                amd64:
                  arm-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-amd64-arm-executor"
                  amd-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-amd64-amd-executor"
                armv7:
                  arm-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-armv7-arm-executor"
                  amd-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-armv7-amd-executor"
                i386:
                  arm-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-i386-arm-executor"
                  amd-executor: "publish-rtl4332mqtt-interlogix-autodiscovery-i386-amd-executor"
          config-path: .circleci/continue_config.yml